[package]
name = "auctioneer_modules"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
anchor-lang = "0.23.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0.60", features = ["full"] }
auctioneer-syn = { path = "../syn", version = "0.1.0" }